### ISSUE TITLE
Function ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by ikeliec** [bitpay/php-bitpay-light-client#10]
Hello Team,
Kudos to the work you have put out here. I appreciate the effort you guys have put in to bring this package out here. 👍 

I am trying to implement this is a laravel project. But I am stuck. I am getting the below error.

`Function ReflectionType::__toString() is deprecated`

This is my first time of implementing bitpay.

Thanks 👍

**Comment by anbugal** [comment]
Hi @ikeliec,
In order to help you with this issue you need to provide more information like context and logs, because that error is very generic and it does not seem to be happening in this library.

ReflectionType::__toString() was deprecated on PHP 7.1.0 and this library is supported by the latest version.

Make sure you do not have other dependencies causing this issue.

**Comment by ikeliec** [comment]
Hi @anbugal, I just figured it out. 

What I did was to change the below line of statement on line 393 of JsonMapper.php

`return [true, $rmeth, $ptype.$nullability];`

to

`return [true, $rmeth, $ptype->getName().$nullability];`

Thank you so much for your time.
